name: quickstart
description: An absolute bare-bones web angular app.
# version: 1.0.0
#homepage: https://www.example.com
#author: Piyush Mehta <me@piyushmehta.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
angular: ^5.0.0

dev_dependencies:
  angular_test: ^2.0.0
  build_runner: ^1.0.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.0.0